### ISSUE TITLE
`window` is not defined

### ISSUE THREAD

**Issue by 6xtvo** [widgetbot-io/react-embed#3]
Hello, I'm using the widgetbot.io react-embed NPM package in my website which I am using with [NextJS](https://nextjs.org). I created a component for it like so:
```js
import WidgetBot from "@widgetbot/react-embed";

export default function Chat() {
    return <WidgetBot server="id" channel="id" />
};
```
And then I imported the component in a page file. However, when I try to run the code, I get this error:
```cmd
error - ReferenceError: window is not defined
    at new Client (C:\Users\ascen\OneDrive\Documents\Programming\Websites\MatrixWebsite\client\node_modules\@widgetbot\embed-api\dist\client.js:27:9)
    at new WidgetBot (C:\Users\ascen\OneDrive\Documents\Programming\Websites\MatrixWebsite\client\node_modules\@widgetbot\react-embed\dist\index.js:14:20)
    at processChild (C:\Users\ascen\OneDrive\Documents\Programming\Websites\MatrixWebsite\client\node_modules\react-dom\cjs\react-dom-server.node.development.js:3305:14)
    at resolve (C:\Users\ascen\OneDrive\Documents\Programming\Websites\MatrixWebsite\client\node_modules\react-dom\cjs\react-dom-server.node.development.js:3270:5)
    at ReactDOMServerRenderer.render (C:\Users\ascen\OneDrive\Documents\Programming\Websites\MatrixWebsite\client\node_modules\react-dom\cjs\react-dom-server.node.development.js:3753:22)
    at ReactDOMServerRenderer.read (C:\Users\ascen\OneDrive\Documents\Programming\Websites\MatrixWebsite\client\node_modules\react-dom\cjs\react-dom-server.node.development.js:3690:29)
    at Object.renderToString (C:\Users\ascen\OneDrive\Documents\Programming\Websites\MatrixWebsite\client\node_modules\react-dom\cjs\react-dom-server.node.development.js:4298:27)
    at Object.renderPage (C:\Users\ascen\OneDrive\Documents\Programming\Websites\MatrixWebsite\client\node_modules\next\dist\server\render.js:596:45)
    at Function.getInitialProps (C:\Users\ascen\OneDrive\Documents\Programming\Websites\MatrixWebsite\client\.next\server\pages\_document.js:618:19)
    at Object.loadGetInitialProps (C:\Users\ascen\OneDrive\Documents\Programming\Websites\MatrixWebsite\client\node_modules\next\dist\shared\lib\utils.js:69:29) {
  page: '/'
}
```

**Comment by njho** [comment]
@r1zyn how did you manage to solve this? Similar error over here

**Comment by r1zyn** [comment]
```

**Comment by r1zyn** [comment]
```
 async function crate()  {
      const result = await import("@widgetbot/crate");
      const Crate = await result.cdn();

      new Crate({
          server: "server id",
          channel: "channel id"
      });
  };

  crate();
```

I put this inside a `useEffect` hook in my `_app.tsx` file (since I'm using Next.js)

**Comment by 6xtvo** [comment]
> @r1zyn how did you manage to solve this? Similar error over here

```ts
 async function crate()  {
      const result = await import("@widgetbot/crate");
      const Crate = await result.cdn();

      new Crate({
          server: "server id",
          channel: "channel id"
      });
  };

  crate();
```

I put this inside a `useEffect` hook in my `_app.tsx` file (since I'm using Next.js)
